@url = http://localhost:8080
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJGaWxtZXMgQVBJIiwic3ViIjoiYWRtaW4iLCJleHAiOjE3NjM0MTg5NDB9.3H19QtEBzIoV8KmS9dA60DboJNelT9Uj9FENPpT1whc

POST {{url}}/cursos
Authorization:  Bearer {{token}}
Content-Type: application/json

{
    "nome" : "Agronomia",
    "descricao" : "Descrição do curso",
    "cargaHoraria" : 40,
    "status" : "ativo",
    "dataCriacao" : "2023-10-10T10:00:00"
}

###
GET {{url}}/cursos
Authorization:  Bearer {{token}}

###
PUT {{url}}/cursos/2
Authorization:  Bearer {{token}}
Content-Type: application/json

{
    "nome" : "Ciencia de dados",
    "descricao" : "Descrição do curso Atualizada",
    "cargaHoraria" : 45,
    "status" : "inativo",
    "dataCriacao" : "2023-10-11T11:00:00"
}

###
GET {{url}}/cursos/2
Authorization:  Bearer {{token}}

###
DELETE {{url}}/cursos/1
Authorization:  Bearer {{token}}