@url = http://localhost:8080

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJGaWxtZXMgQVBJIiwic3ViIjoiYWRtaW4iLCJleHAiOjE3NjM1MDM2NTZ9.ksPrc7hAcUMAYrxJAII6u1zUslJ_Ry4x_XxFDpKeuuY

POST {{url}}/matriculas
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "alunoId": 1,
    "cursoId": 2
}

###
GET {{url}}/matriculas
Authorization: Bearer {{token}}

###
PUT {{url}}/matriculas/2
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "alunoId": 1,
    "cursoId": 3
}

###
DELETE {{url}}/matriculas/1
Authorization: Bearer {{token}}